package indexer

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/jtsilverman/skillscore/internal/analyzer"
	gh "github.com/jtsilverman/skillscore/internal/github"
)

// IndexEntry is a scored skill in the index.
type IndexEntry struct {
	Name        string              `json:"name"`
	Description string              `json:"description"`
	Repo        string              `json:"repo"`
	Path        string              `json:"path"`
	Grade       string              `json:"grade"`
	Score       float64             `json:"score"`
	Dimensions  IndexDimensions     `json:"dimensions"`
	Suggestions []analyzer.Suggestion `json:"suggestions"`
	Source      string              `json:"source"`
}

// IndexDimensions holds per-dimension scores for the web UI.
type IndexDimensions struct {
	Structure   float64 `json:"structure"`
	Description float64 `json:"description"`
	Content     float64 `json:"content"`
	Engineering float64 `json:"engineering"`
	Packaging   float64 `json:"packaging"`
}

// Index is the full output written to scored-index.json.
type Index struct {
	Skills    []IndexEntry `json:"skills"`
	Count     int          `json:"count"`
	Sources   []string     `json:"sources"`
	Generated string       `json:"generated"`
}

// LocalSource represents a local directory of skills to index.
type LocalSource struct {
	Path  string // Absolute path to directory containing skill subdirs
	Label string // e.g., "Local Skills"
	Repo  string // GitHub repo to link to (optional, for display)
}

// RunIndex crawls all default sources, scores each skill, and writes the index.
func RunIndex(outputPath string) error {
	return RunIndexFull(DefaultSources, nil, outputPath)
}

// RunIndexFull crawls GitHub sources and local sources, then writes the index.
func RunIndexFull(sources []Source, localSources []LocalSource, outputPath string) error {
	var mu sync.Mutex
	var entries []IndexEntry
	var sourceLabels []string
	var wg sync.WaitGroup

	for _, src := range sources {
		sourceLabels = append(sourceLabels, fmt.Sprintf("%s/%s", src.Owner, src.Repo))
		wg.Add(1)
		go func(s Source) {
			defer wg.Done()
			results := indexSource(s)
			mu.Lock()
			entries = append(entries, results...)
			mu.Unlock()
		}(src)
	}

	// Index local sources
	for _, ls := range localSources {
		sourceLabels = append(sourceLabels, ls.Label)
		wg.Add(1)
		go func(l LocalSource) {
			defer wg.Done()
			results := indexLocalSource(l)
			mu.Lock()
			entries = append(entries, results...)
			mu.Unlock()
		}(ls)
	}

	wg.Wait()

	idx := Index{
		Skills:    entries,
		Count:     len(entries),
		Sources:   sourceLabels,
		Generated: fmt.Sprintf("generated by skillscore at %s", time.Now().UTC().Format(time.RFC3339)),
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	defer f.Close()

	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	return enc.Encode(idx)
}

// indexLocalSource walks a local directory and scores all skills found.
func indexLocalSource(ls LocalSource) []IndexEntry {
	var entries []IndexEntry

	fmt.Fprintf(os.Stderr, "Indexing local: %s\n", ls.Path)

	// Walk directory tree to find SKILL.md files
	filepath.Walk(ls.Path, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if !info.IsDir() && strings.EqualFold(info.Name(), "SKILL.md") {
			skillDir := filepath.Dir(path)
			report, err := analyzer.AnalyzeSkill(skillDir)
			if err != nil {
				fmt.Fprintf(os.Stderr, "  Skip %s: %v\n", skillDir, err)
				return nil
			}

			// Use the directory name as the path for display
			relPath := filepath.Base(skillDir)

			entries = append(entries, IndexEntry{
				Name:        report.Name,
				Description: report.Desc,
				Repo:        ls.Repo,
				Path:        relPath,
				Grade:       report.Overall.Grade,
				Score:       report.Overall.Points,
				Dimensions: IndexDimensions{
					Structure:   report.Structure.Points,
					Description: report.Description.Points,
					Content:     report.Content.Points,
					Engineering: report.Engineering.Points,
					Packaging:   report.Packaging.Points,
				},
				Suggestions: report.Suggestions,
				Source:      ls.Label,
			})

			fmt.Fprintf(os.Stderr, "  %s %s (%.0f)\n", report.Overall.Grade, report.Name, report.Overall.Points)
		}
		return nil
	})

	fmt.Fprintf(os.Stderr, "  Indexed %d local skills\n", len(entries))
	return entries
}

func indexSource(src Source) []IndexEntry {
	var entries []IndexEntry

	// Try to discover SKILL.md files by fetching the directory listing
	spec := fmt.Sprintf("%s/%s", src.Owner, src.Repo)
	if src.Path != "" {
		spec += "/" + src.Path
	}

	// Discover skill directories using GitHub API
	skillPaths := discoverSkills(src)

	for _, skillPath := range skillPaths {
		fullSpec := fmt.Sprintf("%s/%s/%s", src.Owner, src.Repo, skillPath)
		tmpDir, cleanup, err := gh.FetchSkill(fullSpec)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  Skip %s: %v\n", fullSpec, err)
			continue
		}

		report, err := analyzer.AnalyzeSkill(tmpDir)
		cleanup()
		if err != nil {
			fmt.Fprintf(os.Stderr, "  Skip %s: %v\n", fullSpec, err)
			continue
		}

		entries = append(entries, IndexEntry{
			Name:        report.Name,
			Description: report.Desc,
			Repo:        fmt.Sprintf("%s/%s", src.Owner, src.Repo),
			Path:        skillPath,
			Grade:       report.Overall.Grade,
			Score:       report.Overall.Points,
			Dimensions: IndexDimensions{
				Structure:   report.Structure.Points,
				Description: report.Description.Points,
				Content:     report.Content.Points,
				Engineering: report.Engineering.Points,
				Packaging:   report.Packaging.Points,
			},
			Suggestions: report.Suggestions,
			Source:      src.Label,
		})

		fmt.Fprintf(os.Stderr, "  %s %s (%.0f)\n", report.Overall.Grade, report.Name, report.Overall.Points)
	}

	return entries
}

func discoverSkills(src Source) []string {
	// Use Git Tree API (no 1000-item cap) with Contents API fallback
	allPaths, err := gh.TreeDiscover(src.Owner, src.Repo)
	if err != nil {
		fmt.Fprintf(os.Stderr, "  Tree API failed for %s/%s, falling back to Contents API: %v\n", src.Owner, src.Repo, err)
		return discoverSkillsFallback(src)
	}

	// Filter paths to those under src.Path prefix
	var paths []string
	for _, p := range allPaths {
		if src.Path == "" {
			paths = append(paths, p)
		} else if strings.HasPrefix(p, src.Path+"/") || p == src.Path {
			paths = append(paths, p)
		}
	}

	fmt.Fprintf(os.Stderr, "  Discovered %d skills in %s/%s\n", len(paths), src.Owner, src.Repo)
	return paths
}

// discoverSkillsFallback uses the Contents API (capped at 1000 items) as a fallback.
func discoverSkillsFallback(src Source) []string {
	basePath := src.Path
	entries, err := gh.ListDir(src.Owner, src.Repo, basePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "  Cannot list %s/%s/%s: %v\n", src.Owner, src.Repo, basePath, err)
		return nil
	}

	var paths []string
	for _, e := range entries {
		if e.Type == "dir" {
			subPath := e.Path
			subEntries, err := gh.ListDir(src.Owner, src.Repo, subPath)
			if err != nil {
				continue
			}
			for _, se := range subEntries {
				if se.Name == "SKILL.md" {
					paths = append(paths, subPath)
					break
				}
			}
		} else if e.Name == "SKILL.md" {
			paths = append(paths, basePath)
			break
		}
	}
	return paths
}

