package indexer

import (
	"encoding/json"
	"fmt"
	"os"
	"sync"

	"github.com/jtsilverman/skillscore/internal/analyzer"
	gh "github.com/jtsilverman/skillscore/internal/github"
)

// IndexEntry is a scored skill in the index.
type IndexEntry struct {
	Name        string              `json:"name"`
	Description string              `json:"description"`
	Repo        string              `json:"repo"`
	Path        string              `json:"path"`
	Grade       string              `json:"grade"`
	Score       float64             `json:"score"`
	Dimensions  IndexDimensions     `json:"dimensions"`
	Suggestions []analyzer.Suggestion `json:"suggestions"`
	Source      string              `json:"source"`
}

// IndexDimensions holds per-dimension scores for the web UI.
type IndexDimensions struct {
	Structure   float64 `json:"structure"`
	Description float64 `json:"description"`
	Content     float64 `json:"content"`
	Engineering float64 `json:"engineering"`
	Packaging   float64 `json:"packaging"`
}

// Index is the full output written to scored-index.json.
type Index struct {
	Skills    []IndexEntry `json:"skills"`
	Count     int          `json:"count"`
	Sources   []string     `json:"sources"`
	Generated string       `json:"generated"`
}

// RunIndex crawls all default sources, scores each skill, and writes the index.
func RunIndex(outputPath string) error {
	return RunIndexWithSources(DefaultSources, outputPath)
}

// RunIndexWithSources crawls the given sources and writes the index.
func RunIndexWithSources(sources []Source, outputPath string) error {
	var mu sync.Mutex
	var entries []IndexEntry
	var sourceLabels []string
	var wg sync.WaitGroup

	for _, src := range sources {
		sourceLabels = append(sourceLabels, fmt.Sprintf("%s/%s", src.Owner, src.Repo))
		wg.Add(1)
		go func(s Source) {
			defer wg.Done()
			results := indexSource(s)
			mu.Lock()
			entries = append(entries, results...)
			mu.Unlock()
		}(src)
	}

	wg.Wait()

	idx := Index{
		Skills:    entries,
		Count:     len(entries),
		Sources:   sourceLabels,
		Generated: "generated by skillscore",
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	defer f.Close()

	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	return enc.Encode(idx)
}

func indexSource(src Source) []IndexEntry {
	var entries []IndexEntry

	// Try to discover SKILL.md files by fetching the directory listing
	spec := fmt.Sprintf("%s/%s", src.Owner, src.Repo)
	if src.Path != "" {
		spec += "/" + src.Path
	}

	// Discover skill directories using GitHub API
	skillPaths := discoverSkills(src)

	for _, skillPath := range skillPaths {
		fullSpec := fmt.Sprintf("%s/%s/%s", src.Owner, src.Repo, skillPath)
		tmpDir, cleanup, err := gh.FetchSkill(fullSpec)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  Skip %s: %v\n", fullSpec, err)
			continue
		}

		report, err := analyzer.AnalyzeSkill(tmpDir)
		cleanup()
		if err != nil {
			fmt.Fprintf(os.Stderr, "  Skip %s: %v\n", fullSpec, err)
			continue
		}

		entries = append(entries, IndexEntry{
			Name:        report.Name,
			Description: report.Desc,
			Repo:        fmt.Sprintf("%s/%s", src.Owner, src.Repo),
			Path:        skillPath,
			Grade:       report.Overall.Grade,
			Score:       report.Overall.Points,
			Dimensions: IndexDimensions{
				Structure:   report.Structure.Points,
				Description: report.Description.Points,
				Content:     report.Content.Points,
				Engineering: report.Engineering.Points,
				Packaging:   report.Packaging.Points,
			},
			Suggestions: report.Suggestions,
			Source:      src.Label,
		})

		fmt.Fprintf(os.Stderr, "  %s %s (%.0f)\n", report.Overall.Grade, report.Name, report.Overall.Points)
	}

	return entries
}

func discoverSkills(src Source) []string {
	basePath := src.Path
	entries, err := gh.ListDir(src.Owner, src.Repo, basePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "  Cannot list %s/%s/%s: %v\n", src.Owner, src.Repo, basePath, err)
		return nil
	}

	var paths []string
	for _, e := range entries {
		if e.Type == "dir" {
			subPath := e.Path
			subEntries, err := gh.ListDir(src.Owner, src.Repo, subPath)
			if err != nil {
				continue
			}
			for _, se := range subEntries {
				if se.Name == "SKILL.md" {
					paths = append(paths, subPath)
					break
				}
			}
		} else if e.Name == "SKILL.md" {
			paths = append(paths, basePath)
			break
		}
	}
	return paths
}

